spring:
  datasource:
    # 这是主库 (master)，代码默认读取路径
    url: jdbc:mysql://127.0.0.1:3306/zh-diyproject?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
    username: root
    password: root123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

xzh:
  datasource:
    log:
      enabled: true
      db-name: zh-log #
      url: jdbc:mysql://127.0.0.1:3306/zh-log?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
      username: root
      password: root123456789